### ISSUE TITLE
Tạo giao diện trang chủ Admin

### ISSUE THREAD

**Issue by linhngan17** [CNPM-RoomManagement/RoomManagement#6]

**Comment by linhngan17** [comment]
Thao làm thử view cho home Admin nhé

**Comment by NguyenThiThao98** [comment]
ok

**Comment by linhngan17** [comment]
Hạn cuối tối thứ 4 nhé

**Comment by NguyenThiThao98** [comment]
t không tạo được biểu đồ. tìm hiểu trên mạng có cái thư viện chart.js để vẽ biểu đồ mà tải về lại không giống hướng dẫn trên mạng, không có file chart.min.js. Không biết vẽ thế nào cả

**Comment by linhngan17** [comment]
tạm thời vẽ biểu đồ chết đã nhé

**Comment by linhngan17** [comment]
Chốt là admin vẫn giữ như cũ nhé
