### ISSUE TITLE
Validate account details

### ISSUE THREAD

**Issue by linhngan17** [CNPM-RoomManagement/RoomManagement#8]
Validate account lúc đăng ký tài khoản mới nhé, và cả phần update thông tin cá nhân nữa @sonnguyezz

**Comment by sonnguyezz** [comment]
cần update những thông tin gì vậy

**Comment by sonnguyezz** [comment]
phải kiểm tra cả tài khoản có trùng hay không

**Comment by linhngan17** [comment]
T mới chỉ ktra tài khoản đã tồn tại chưa thôi, m phải ktra user vs password, set điều kiện cho nó cho nó chặt chẽ hơn một xíu, ví dụ như user thì không được có dấu cách..v..v

**Comment by sonnguyezz** [comment]
nghe vẻ căng :3 t nghĩ nhiều cái mà khả năng ko làm đc -.-

**Comment by linhngan17** [comment]
thử đi, có chỗ nào mắc thì cmt ở đây hoặc hỏi bác Google =)))

**Comment by linhngan17** [comment]
Hạn cuối tối thứ 4 nhé

**Comment by linhngan17** [comment]
đã đẩy code lên rồi nhé

**Comment by sonnguyezz** [comment]
đã đẩy code lên rồi nhé
